ammobinDOTca/ammobin-api

index.js, package.json, the-ammo-source.js, wild-west.js
=> added wild west aka gun-shop.ca

index.js, the-ammo-source.js
- properly format track click link to account for url already having search params (ammo source)
- properly pull img for ammo source
=> fix some things

.vscode/cSpell.json, cabelas-api.js, index.js, package.json
- added remaining rifle rounds
- removed natural and used hard coded alternative
- fixed incorrect link to store bug
=> fixed up calbelas

index.js, influx.js, move-clicks.js
- created script to move old redis clicks
- removed redis insert
=> moved clicks to influx

.eslintrc.js, .vscode/cSpell.json, canadian-tire.js, hirschprecision.js, index.js, jo-brook.js, mapdump.js, move-clicks.js, rangeviewsports.js, the-ammo-source.js, tiger-arms.js, wild-west.js
- disabled rules i dont care about
- moved some apis into own file
- removed some consoles + commented out code
=> cleaned up some code

helpers.js, index.js, influx.js
- get item from redis + save info in influx
=> log more details about what was clicked

index.js, tradex.js
- need to update classifier to parse their detailed descriptions
=> added tradeexcanda.com

cabelas-api.js, helpers.js, index.js
- only combine truely results
- fixed 2 silly errors. VERY BAD
- also now sending custom user agent string (to be nice)
- moved stuff around in index
=> hot fix cabelas

bvoutdoors.js, frontierfirearms.js, index.js, the-ammo-source.js
- also fixed silly bug where list item index was being passed to the get + parse page function as the page number
- removed some old comments
=> added bvoutdoors.com

index.js, package.json
- finally figured hapi caching
- should make a blog post about how to get it all working...
todo
- update scrape cycle
- user only ever sees what was already in cache (no more waiting for it to load)
- handle case where user hits site at  00:00 UTC => return yesterday's data if none exists for today
=> enable api caching (in progress)

Dockerfile
- https://nodesource.com/blog/8-protips-to-start-killing-it-when-dockerizing-node-js/
=> testing adding dump init to docker container

Dockerfile
Reverts ammobinDOTca/ammobin-api#51
handled in docker-compose file
=> Revert "testing adding dump init to docker container"

index.js, the-ammo-source.js
- should allow us to not run out of memory
=> run scrapes one at a time

bvoutdoors.js, cabelas-api.js, frontierfirearms.js, tenda.js, tiger-arms.js
- fixed calbelas sneaking in their own calibres
=> throttle even more stuff

index.js
- let docker-compose restart container
fixes #57
=> crash server when 500 occurs 

src/scrapes/bvoutdoors.js, src/scrapes/the-ammo-source.js, src/scrapes/tiger-arms.js, src/scrapes/tradex.js
- could fix out of memory issues in prod
- if does not work, will have to retrun promise w/ items + load next page flag, then call function again
=> dont hold onto cheerio of page when loading mutliple pages

package.json
=> fix(package): update ammobin-classifier to version 0.0.18

src/constants.js, src/random/test.js, src/scrapes/index.js, src/scrapes/leverarms.js, src/scrapes/wanstalls.js.bak, src/scrapes/westcoasthunting.js.bak
- added some blocked scrapes as well....
=> added levelarms

package.json
Reverts ammobinDOTca/ammobin-api#86
=> Revert "Update hapi-cron to the latest version 🚀"

src/api/index.js
- should no be denyed click b/c influx is being fucky
=> always allow user to click through

package.json
=> fix(package): update ammobin-classifier to version 0.0.26

src/api/graphql-lambda.ts
=> convert rawPath to path

src/api/graphql-lambda.ts
=> guard against missing prop
